DROP TABLE OM_STOCK1
TRUNCATE TABLE OM_STOCK1
CREATE TABLE OM_STOCK1
(
ITEMID VARCHAR(10) CHECK (LEN(ITEMID)=5 AND ITEMID LIKE 'I%' AND(ITEMID LIKE '__P%' OR ITEMID LIKE'__M%')) PRIMARY KEY,
ITEM_NAME VARCHAR(45),
PRICE FLOAT CHECK(PRICE>0),
QTY INT CHECK(QTY>0),
SOLD_DATE DATETIME
)

CREATE PROC SP_OM_STOCK1 
(
@ITEMID VARCHAR(10),
@ITEM_NAME VARCHAR(45),
@PRICE FLOAT,
@QTY INT
)
AS
BEGIN
	INSERT INTO OM_STOCK1 VALUES(@ITEMID,@ITEM_NAME,@PRICE,@QTY,GETDATE())
END

EXEC SP_OM_STOCK1 'IKP36','BAG',25.55,45
EXEC SP_OM_STOCK1 'IKM40','PEN',15.10,50
EXEC SP_OM_STOCK1 'IKP33','SHOES',55.66,65
EXEC SP_OM_STOCK1 'ILM50','BOOKS',33.12,150
EXEC SP_OM_STOCK1 'IBMKK','CAR',22325.55,35
EXEC SP_OM_STOCK1 'ITP55','APPLE',5.65,333

SELECT * FROM OM_STOCK1 


DROP TABLE OM_SALE1  
SELECT * FROM OM_SALE1 

TRUNCATE TABLE OM_SALE1

CREATE TABLE OM_SALE1
(
ITEMID VARCHAR(10) CHECK (LEN(ITEMID)=5 AND ITEMID LIKE 'I%' AND(ITEMID LIKE '__P%' OR ITEMID LIKE'__M%')) FOREIGN KEY REFERENCES OM_STOCK1(ITEMID),
QTY INT CHECK(QTY>0),
SOLD_DATE DATETIME
)
DROP PROC SP_NET_STOCK1 
CREATE PROC SP_NET_STOCK1 
(
@ITEMID VARCHAR(10),
@QTY INT
)
AS
BEGIN
	INSERT INTO OM_SALE1 VALUES(@ITEMID,@QTY,GETDATE())
	UPDATE OM_STOCK1 
	SET QTY= QTY-@QTY
	FROM OM_STOCK1 OM WHERE ITEMID=@ITEMID  
END	

EXEC SP_NET_STOCK1 'ILM50',4
EXEC SP_NET_STOCK1 'ITP55',3

DROP TABLE OM_NEED_TO_BE_ORDER
CREATE TABLE OM_NEED_TO_BE_ORDER
(
ITEMID VARCHAR(10) CHECK (LEN(ITEMID)=5 AND ITEMID LIKE 'I%' AND(ITEMID LIKE '__P%' OR ITEMID LIKE'__M%')) FOREIGN KEY REFERENCES OM_STOCK1(ITEMID),
UPDATE_DATE DATETIME
)

SELECT * FROM OM_NEED_TO_BE_ORDER

DROP PROC SP_NET_STOCK1 
ALTER PROC SP_NET_STOCK1  
(
@ITEMID VARCHAR(10),
@QTY INT
)
AS
BEGIN
	
	IF(SELECT @QTY FROM OM_STOCK1 WHERE ITEMID=@ITEMID)<5
BEGIN
	INSERT INTO OM_NEED_TO_BE_ORDER VALUES(@ITEMID,GETDATE())
END
	
	INSERT INTO OM_SALE1 VALUES(@ITEMID,@QTY,GETDATE())
	UPDATE OM_STOCK1
	SET QTY= QTY-@QTY
	FROM OM_STOCK1 OM WHERE ITEMID=@ITEMID  
END	

EXEC SP_NET_STOCK1 'IKP36', 2
EXEC SP_NET_STOCK1 'ITP55', 3

SELECT * FROM OM_STOCK1
SELECT * FROM OM_SALE1
SELECT * FROM OM_NEED_TO_BE_ORDER

