
DROP TABLE OMSIR_FILENAME_TABLE

CREATE TABLE OMSIR_FILENAME_TABLE
(
FILENAME VARCHAR(50)
)

SELECT * FROM OMSIR_FILENAME_TABLE

INSERT INTO OM_FILENAME_TABLE VALUES
('EMPLOYEE_2019219.HTML'),
('EMPLOYEE_20190219.HTML'),
('DEPARTMENT_20201109.CSV'),
('SALES_2018623.RD')

SELECT * FROM OMSIR_FILENAME_TABLE

SELECT SUBSTRING(FILENAME,0,CHARINDEX ('_',FILENAME,1)) AS FILENAME,
SUBSTRING(FILENAME,CHARINDEX('_',FILENAME,1)+1,CHARINDEX('.',FILENAME)-CHARINDEX('_',FILENAME,1)-1) AS DATE,
SUBSTRING(FILENAME,CHARINDEX('.',FILENAME,1)+1, LEN(FILENAME))AS ENTENTION FROM OMSIR_FILENAME_TABLE


 