DROP TABLE Omsir_class_practice.EMPLOYEE

SELECT * FROM Omsir_class_practice.EMPLOYEE

--DISPLAY SALARY BY RANGE 
--ANS:

SELECT SALARY
FROM Omsir_class_practice.EMPLOYEE WHERE SALARY BETWEEN 0 AND 300 

SELECT SALARY
FROM Omsir_class_practice.EMPLOYEE WHERE SALARY BETWEEN 301 AND 1000 

SELECT SALARY
FROM Omsir_class_practice.EMPLOYEE WHERE SALARY BETWEEN 1001 AND 2000 

SELECT SALARY
FROM Omsir_class_practice.EMPLOYEE WHERE SALARY > = 2001 

--OR, IF WE NEED ALL INFORMATION THAN WE CAN DO LIKE AS FOLLOWING:

SELECT * FROM Omsir_class_practice.EMPLOYEE WHERE SALARY BETWEEN 0 AND 300
SELECT * FROM Omsir_class_practice.EMPLOYEE WHERE SALARY BETWEEN 301 AND 1000 
SELECT * FROM Omsir_class_practice.EMPLOYEE WHERE SALARY BETWEEN 1001 AND 2000
SELECT * FROM Omsir_class_practice.EMPLOYEE WHERE SALARY > = 2001



