DROP TABLE Omsir_class_practice.BAD_DATA_EMPLOYEE

DROP TABLE Omsir_class_practice.GOOD_DATA_EMPLOYEE 


CREATE TABLE Omsir_class_practice.BAD_DATA_EMPLOYEE
(
EMP_ID VARCHAR (50),
FIRSTNAME VARCHAR (45),
LASTNAME VARCHAR (45),
DOB DATETIME 
)

INSERT INTO [Omsir_class_practice].[BAD_DATA_EMPLOYEE] VALUES
('E01','tom','brandy',2/23/2001),
('E02','russ','smiTH',3/23/1990),
('e03','ERIKA',	'RANA',2/3/1998),
('e04','NEENA','KC',3/23/1997),
('E05','URIKa','hightowER',12/3/1098)


SELECT UPPER (EMP_ID) AS EMP_ID,
UPPER (LEFT(((RTRIM(LTRIM(FIRSTNAME)))),1))+ LOWER(SUBSTRING((RTRIM(LTRIM(FIRSTNAME))),2,LEN(FIRSTNAME))) AS FIRSTNAME,
UPPER (LEFT(((RTRIM(LTRIM(LASTNAME)))),1))+ LOWER(SUBSTRING((RTRIM(LTRIM(LASTNAME))),2,LEN(LASTNAME))) AS LASTNAME,
DATEDIFF(YY,DOB,GETDATE()) AS EASY_AGE, datediff(yy,DOB,getdate())- (CASE WHEN month(DOB)> month(getdate()) THEN 1 
WHEN (month(DOB)=month(getdate()) AND day(DOB)>day(getdate())) THEN 1 
ELSE 0 END) AS EXACT_AGE
INTO Omsir_class_practice.GOOD_DATA_EMPLOYEE 
FROM Omsir_class_practice.BAD_DATA_EMPLOYEE

--OR WE CAN USE (REPLACE(FIRSTNAME,SPACE(1),'')     INSTEAD OF        (RTRIM(LTRIM(FIRSTNAME))

SELECT UPPER (EMP_ID) AS EMP_ID,
UPPER (LEFT(((REPLACE(FIRSTNAME,SPACE(1),''))),1))+ LOWER(SUBSTRING((REPLACE(FIRSTNAME,SPACE(1),'')),2,LEN(FIRSTNAME))) AS FIRSTNAME,
UPPER (LEFT(((RTRIM(LTRIM(LASTNAME)))),1))+ LOWER(SUBSTRING((RTRIM(LTRIM(LASTNAME))),2,LEN(LASTNAME))) AS LASTNAME,
DATEDIFF(YY,DOB,GETDATE()) AS EASY_AGE, datediff(yy,DOB,getdate())- (CASE WHEN month(DOB)> month(getdate()) THEN 1 
WHEN (month(DOB)=month(getdate()) AND day(DOB)>day(getdate())) THEN 1 
ELSE 0 END) AS EXACT_AGE

FROM Omsir_class_practice.BAD_DATA_EMPLOYEE











SELECT * FROM Omsir_class_practice.GOOD_DATA_EMPLOYEE

SELECT * FROM Omsir_class_practice.BAD_DATA_EMPLOYEE

