DROP TABLE OM_GENDER_TABLE
CREATE TABLE OM_GENDER_TABLE
(
EMPID INT IDENTITY(1,1),
GENDER VARCHAR(20)
)
INSERT INTO OM_GENDER_TABLE VALUES 
('M'), ('  M A LE'), ('  F'), (' FE MAL E'), 
('F'), ('M  '), ('FE'), (' MAL '), ('U '), (' AL '), (' EMALE'), ('FAN'), (' MSLE')

SELECT * FROM OM_GENDER_TABLE


SELECT replace(GENDER,space(1),'')
FROM OM_GENDER_TABLE


FROM OM_GENDER_TABLE

--REQUIREMENT: DISPLAY AS FOLLOWING
CREATE FUNCTION WHERE YOU GET ONLY 'M', 'F' OR NULL. 

DROP FUNCTION DBO.GENDER_TABLE
CREATE FUNCTION DBO.GENDER_TABLE(@EMP_GENDER VARCHAR (10))
RETURNS VARCHAR(10)
AS
BEGIN
DECLARE @GENDER VARCHAR (10)
SET @GENDER=@EMP_GENDER
SET @GENDER= replace(@GENDER,space(1),'')
IF @GENDER LIKE 'F%' 
BEGIN
SET @GENDER= 'F'
 END

ELSE IF @GENDER LIKE 'M%'

 BEGIN
 SET @GENDER = 'M'
 END
 ELSE
BEGIN
SET @GENDER=NULL
END
RETURN @GENDER
END


--EXECUTING THE FUNCTION

SELECT GENDER, DBO.GENDER_TABLE(GENDER) AS GENDER_IN_SHORT FROM OM_GENDER_TABLE 
