DROP TABLE Omsir_class_practice.FILENAME
DROP TABLE NORMALIZED_TABLE
 CREATE TABLE Omsir_class_practice.FILENAME
(
FILENAME VARCHAR(45)
)

INSERT INTO Omsir_class_practice.FILENAME VALUES
('EMPLOYEE_20190219.TXT'),		
('DEPARTMENT_20201109.CSV'),		
('SALES_20180623.XLE')		
	
SELECT * FROM Omsir_class_practice.FILENAME		

SELECT SUBSTRING ([FILENAME],1,CHARINDEX ('_',[FILENAME])-1) AS FILENAME_ONLY,
SUBSTRING ([FILENAME],CHARINDEX('_',[FILENAME])+1, 
LEN([FILENAME])-CHARINDEX ('.',FILENAME)+5) AS DATE,
SUBSTRING ([FILENAME],CHARINDEX('.',[FILENAME])+1, 
LEN([FILENAME])-CHARINDEX ('.',[FILENAME])) AS EXTENTION
INTO NORMALIZED_TABLE FROM [Omsir_class_practice].[FILENAME]


SELECT * FROM [Omsir_class_practice].[FILENAME]


SELECT*FROM NORMALIZED_TABLE

