		
 DROP TABLE Omsir_class_practice.DEPOSIT_SLIP

 CREATE TABLE Omsir_class_practice.DEPOSIT_SLIP
(
ACCOUNT_NO VARCHAR(20),
NAMAE VARCHAR(45),
DATE DATETIME,
DEPOSIT_TO VARCHAR(20),
CASH_COIN_CHECK VARCHAR(20),
DOLLAR FLOAT,
COIN DECIMAL
)

INSERT INTO Omsir_class_practice.DEPOSIT_SLIP VALUES
('0102004510','RAM',02/06/2019,'SAVINGS','CASH',200,.50)	
	
SELECT * FROM Omsir_class_practice.DEPOSIT_SLIP		
		
