DROP TABLE OM_STOCK
CREATE TABLE OM_STOCK
(
ITEMID VARCHAR(10) CHECK (LEN(ITEMID)=5 AND ITEMID LIKE 'I%' AND(ITEMID LIKE '__P%' OR ITEMID LIKE'__M%')) PRIMARY KEY,
ITEM_NAME VARCHAR(45),
PRICE FLOAT CHECK(PRICE>0),
QTY INT CHECK(QTY>0),
SOLD_DATE DATETIME
)

CREATE PROC SP_OM_STOCK 
(
@ITEMID VARCHAR(10),
@ITEM_NAME VARCHAR(45),
@PRICE FLOAT,
@QTY INT
)
AS
BEGIN
	INSERT INTO OM_STOCK VALUES(@ITEMID,@ITEM_NAME,@PRICE,@QTY,GETDATE())
END

EXEC SP_OM_STOCK 'IKP36','BAG',25.55,45
EXEC SP_OM_STOCK 'IKM40','PEN',15.10,50
EXEC SP_OM_STOCK 'IKP33','SHOES',55.66,65
EXEC SP_OM_STOCK 'ILM50','BOOKS',33.12,150
EXEC SP_OM_STOCK 'IBMKK','CAR',22325.55,35
EXEC SP_OM_STOCK 'ITP55','APPLE',5.65,333

SELECT * FROM OM_STOCK


DROP TABLE OM_SALE 
SELECT * FROM OM_SALE

TRUNCATE TABLE OM_SALE

CREATE TABLE OM_SALE
(
ITEMID VARCHAR(10) CHECK (LEN(ITEMID)=5 AND ITEMID LIKE 'I%' AND(ITEMID LIKE '__P%' OR ITEMID LIKE'__M%')) FOREIGN KEY REFERENCES OM_STOCK(ITEMID),
QTY INT CHECK(QTY>0),
SOLD_DATE DATETIME
)
DROP PROC SP_NET_STOCK
CREATE PROC SP_NET_STOCK 
(
@ITEMID VARCHAR(10),
@QTY INT
)
AS
BEGIN
	INSERT INTO OM_SALE VALUES(@ITEMID,@QTY,GETDATE())
	UPDATE OM_STOCK
	SET QTY= QTY-@QTY
	FROM OM_STOCK OM WHERE ITEMID=@ITEMID  
END	

EXEC SP_NET_STOCK 'ILM50',4
EXEC SP_NET_STOCK 'ITP55',3


SELECT * FROM OM_STOCK
SELECT * FROM OM_SALE 
