DROP TABLE OMSIR_FULL_ADDRESS
CREATE TABLE OMSIR_FULL_ADDRESS

(FULL_ADDRESS VARCHAR (50)
)

INSERT INTO OMSIR_FULL_ADDRESS
(345 BELTLINE RD, IRVING, TX, 76898-3400
3005 ROCHELL ROAD, GRAND PARIES, CA, 45222
345 INDUSTRIAL BLVD, EULESS, NY, 34532-3432
8900 WALLNUT HILL APT #340, IRVING, OK, 34500-5675

--ADDRESS1, CITY, STATE, ZIPCODE_5CHAR

SELECT 
SUBSTRING(FULL_ADDRESS,0,CHARINDEX(',',FULL_ADDRESS,1)) ADDRESS1,
SUBSTRING(FULL_ADDRESS,CHARINDEX(',',FULL_ADDRESS)+1,CHARINDEX(',',FULL_ADDRESS,CHARINDEX(',',FULL_ADDRESS)+1)-CHARINDEX(',',FULL_ADDRESS)-1) CITY,
SUBSTRING(FULL_ADDRESS,(CHARINDEX(',',FULL_ADDRESS,CHARINDEX(',',FULL_ADDRESS)+1)+1),3) STATE,
SUBSTRING(FULL_ADDRESS,(CHARINDEX(',',FULL_ADDRESS,CHARINDEX(',',FULL_ADDRESS)+1)+5),6) ZIPCODE_5CHAR
FROM OMSIR_FULL_ADDRESS

SELECT * FROM OMSIR_FULL_ADDRESS

