DROP TABLE OM_FLIPING_DATA
CREATE TABLE OM_FLIPING_DATA 
(
CODE VARCHAR(20)
)			
			
INSERT INTO OM_FLIPING_DATA VALUES
('RAT'),
('PEN'),
('CNNAY'),
('SWIMSA'),
('YUITAG')

SELECT * FROM OM_FLIPING_DATA

SELECT CODE, REVERSE(REPLACE(CODE,'A','Z')) FROM OM_FLIPING_DATA
