DROP schema Omsir_class_practice

DROP TABLE Omsir_class_practice.EMPLOYEES_DTLS

create schema Omsir_class_practice 

CREATE TABLE Omsir_class_practice.EMPLOYEES_DTLS
(
EMPNAME VARCHAR(45),
EMAIL VARCHAR (50)
)

INSERT INTO Omsir_class_practice.EMPLOYEES_DTLS VALUES 
('RAM THAPA','RAM.THAPA@GMAIL.COM'),
('RABIN LUZA','RABIN_LUZA@HOTMAIL.COM'),
('TOM HANK','@GMAIL.COM'),
('ROBIN HOOD','HOOD_RABIN@YAHOO.COM'),
('YUNISH SHARMA','YNISH_SHARMA.COM'),
('JEEVAN RANA','RANA_JEEVAN2001.COM'),
('SUNIL LAMA','SUNIL2012LAMA@YAHOO.COM'),
('RABIN RAI','RAIN..RAI@GMAIL.COM'),
('SURAJ SHRESTHA','SURAJ.@GMAIL.COM'),
('TINA PUN','TINA@.GMAIL.COM')


SELECT * FROM Omsir_class_practice.EMPLOYEES_DTLS

UPDATE Omsir_class_practice.EMPLOYEES_DTLS SET EMAIL='TOM_HANK@GMAIL.COM' WHERE EMAIL= '@GMAIL.COM'

--QUESTION 1:	 DISPLAY POSITION OF @ IN EMAIL COLUMN
--ANS:
ALTER TABLE Omsir_class_practice.EMPLOYEES_DTLS ADD POSITION_OF_@ INT

SELECT CONCAT(EMAIL,POSITION_OF_@) FROM Omsir_class_practice.EMPLOYEES_DTLS 

--QUESTION 2:	DISPLAY ALL WHOSE EMAIL WHICH DO NOT HAVE '@' SIGN	
--ANS:
SELECT EMAIL FROM Omsir_class_practice.EMPLOYEES_DTLS WHERE EMAIL NOT LIKE '%@%'  

--QUESTION 3: 	SEPERATE BEFORE AND AFTER @ SIGN
--ANS:

SELECT SUBSTRING(EMAIL,CHARINDEX (EMAIL,'@'), LEN (EMAIL)-CHARINDEX ('@',EMAIL)) AS BEFORE@,
SUBSTRING(EMAIL,CHARINDEX ('@',EMAIL)+1, LEN (EMAIL)-CHARINDEX ('@',EMAIL)) AS AFTER@ 
FROM Omsir_class_practice.EMPLOYEES_DTLS

--QUESTION 4: 	DISPLAY THOSE EMAIL WHICH HAVE TWO "..", WHICH IS NOT CORRECT EMAIL				
--ANS:
SELECT EMAIL FROM Omsir_class_practice.EMPLOYEES_DTLS WHERE EMAIL LIKE '%..%'

--QUESTION 5: 	DISPLAY ANY EMAIL WHICH HAVE "." BEFORE OR AFTER @ SIGN, , WHICH IS NOT CORRECT EMAIL				

--ANS:
SELECT EMAIL FROM Omsir_class_practice.EMPLOYEES_DTLS WHERE EMAIL LIKE '%.@%' OR EMAIL LIKE '%@.%'

--QUESTION 6: 	DISPLAY ALL BAD EMAIL: 				
--		EMAIL WHICH HAVE "." BEFORE OR AFTER @ SIGN			
--		EMAIL WHICH HAVE TWO ".."			
--		EMAIL WHICH DO NOT HAVE '@' SIGN
--ANS:
SELECT EMAIL FROM Omsir_class_practice.EMPLOYEES_DTLS WHERE (EMAIL LIKE '%.@%') OR (EMAIL LIKE '%@.%') OR (EMAIL LIKE '%..%') OR
(EMAIL NOT LIKE '%@%')

QUESTION 7: 	DISPLAY EMAIL WHICH IS START WITH ANY NUMBER VALUE
--ANS:
SELECT * FROM Omsir_class_practice.EMPLOYEES_DTLS WHERE EMAIL LIKE'[0-9]%'			

QUESTION 8:	DISPLAY EMAIL WHICH IS NOT START WITH ANY NUMBER VALUE				
--ANS:
SELECT EMAIL FROM Omsir_class_practice.EMPLOYEES_DTLS WHERE EMAIL NOT LIKE '[0-9]%'			



