DECLARE @i INT 
SET @i = 0
DECLARE @j INT 
SET @j= 2
PRINT 'Multipliction table for ' 
    + CONVERT(VARCHAR, @j) + ':' + CHAR(13)
WHILE (@i < 10)
BEGIN
 SET @i = @i + 1
 PRINT CONVERT(VARCHAR, @i) + ' x 2 = ' + CONVERT(VARCHAR, @i*@j)
 END

--OR DIRECT CREATED THE TABLE LIKE AS BELOW

DROP TABLE MULTIPLICATION_OF_2

CREATE TABLE MULTIPLICATION_OF_2  
(
MULTIPLICATION_OF_2 VARCHAR (50)
)

INSERT INTO MULTIPLICATION_OF_2 VALUES
('2x1=2'),
('2x2=4'),
('2x3=6'),
('2x4=8'),
('2x5=10'),
('2x6=12'),
('2x7=14'),
('2x8=16'),
('2x9=18'),
('2x10=20')

SELECT * FROM MULTIPLICATION_OF_2






