
DROP TABLE EMAILS_OF_EMPLOYEES
CREATE TABLE EMAILS_OF_EMPLOYEES
(
EMPNAME VARCHAR (25),
EMAILS VARCHAR(30)
)

INSERT INTO EMAILS_OF_EMPLOYEES VALUES

('RAM THAPA','RAMTHAPA@GMAIL.COM'),
('RABIN LUZA','RABINLUZA@HOTMAIL.COM'),
('TOM HANK','TOMHA@GMAIL.COM'),
('ROBIN HOOD','HOODRABIN@YAHOO.COM'),
('YUNISH SHARMA','YNISHSHARMA.COM'),
('JEEVAN RANA','RANAJEEVAN2001.COM'),
('SUNIL LAMA','SUNIL2012LAMA@YAHOO.COM'),
('RABIN RAI','RAINRAI@GMAIL.COM'),
('SURAJ SHRESTHA','SURAJ@GMAIL.COM'),
('TINA PUN','TINA@GMAIL.COM')

SELECT * FROM EMAILS_OF_EMPLOYEES

--USE OF REPLICATE 
--NEED TO PUT S (OR ANY VALUES), 3 (OR ANY TIMES) TIMES AFTER FIRST 3 CHAR OF EMAILS

SELECT *, SUBSTRING(EMAILS,1,3)+REPLICATE('ZORBA',1)+SUBSTRING(EMAILS, CHARINDEX('@',EMAILS), LEN(EMAILS)-CHARINDEX('@',EMAILS)+1) AS NEW_EMAILS
FROM EMAILS_OF_EMPLOYEES


