DROP TABLE OM_FULLNAME

CREATE TABLE OM_FULLNAME
(
EMP_FIRSTNAME VARCHAR(20),
EMP_MIDDLENAME VARCHAR(20),
EMP_LASTNAME VARCHAR(20)
)

INSERT INTO OM_FULLNAME VALUES 
('RAJU','KUMAR','KARKI'), 
('SHYAM',NULL,'RAI'),
('PUKAR','BHAHADUR','PUN'),
('RABIN',NULL,'LAMA')

SELECT * FROM OM_FULLNAME




SELECT*, (EMP_LASTNAME+',' +EMP_FIRSTNAME+','+SUBSTRING(ISNULL(EMP_MIDDLENAME,''),1,1)) AS FULLNAME FROM OM_FULLNAME








