DROP TABLE FISHTAIL_MENU
CREATE TABLE FISHTAIL_MENU
(
ITEM_ID INT IDENTITY (1,1),
CATEGORY VARCHAR(45)
)
INSERT INTO FISHTAIL_MENU VALUES
('NEPALESE_VEG_APPETIZERS'),
('NEPALESE_NON_VEG_ENTREE'),
('INDIAN_VEG_APPETIZERS'),
('INDIAN_NON_VEG_APPETIZERS'),
('INDO_CHINESE_APPETIZERS'),
('NEPALESE_VEG_ENTREE'),
('FISHTAIL_THAKALI_THALI'),
('NEPALESE_NON_VEG_APPETIZERS'),
('INDIAN_VEG_ENTREE'),
('INDIAN_NON_VEG_CHICKEN_ENTRY')
SELECT * FROM FISHTAIL_MENU

DROP TABLE ITEMS
CREATE TABLE ITEMS
(
ITEM_ID INT IDENTITY (1,1),
MENU VARCHAR(45),
CATEGORY VARCHAR (45),
PRICE MONEY
)
INSERT INTO ITEMS VALUES
('VEG_CHOWMEIN','NEPALESE_VEG_APPETIZERS',6.99),
('VEG_MOMO','NEPALESE_VEG_APPETIZERS',5.99),
('ALUKO_ACHAR','NEPALESE_VEG_APPETIZERS',4.99),
('KATHMANDU_CHICKEN','NEPALESE_NON_VEG_ENTREE',10.99),
('PANEER_PAKORA','INDIAN_VEG_APPETIZERS',5.99),
('SAMOSA','INDIAN_VEG_APPETIZERS',3.99),
('CHICKEN_PAKORA','INDIAN_NON_VEG_APPETIZERS',6.99),
('PANEER_CHILLI','INDO_CHINESE_APPETIZERS',7.99),
('CHICKEN_CHILLI','INDO_CHINESE_APPETIZERS',7.99),
('RAYOKO_SAAG','NEPALESE_VEG_ENTREE',8.99),
('ALU_TAMA_BODI','NEPALESE_VEG_ENTREE',9.99),
('VEG_THAKALI_THALI','FISHTAIL_THAKALI_THALI',14.99),
('TAAS','NEPALESE_NON_VEG_APPETIZERS',10.99),
('SEKUWA','NEPALESE_NON_VEG_APPETIZERS',8.99),
('GOBI_MASALA','INDIAN_VEG_ENTREE',10.99),
('PALAK_PANEER','INDIAN_VEG_ENTREE',10.99),
('CHICKEN_CURRY','NEPALESE_VEG_APPETIZERS',6.99),
('CHICKEN_SAAG','INDIAN_NON_VEG_CHICKEN_ENTRY',11.99),
('VEG_CHOWMEIN','INDIAN_NON_VEG_CHICKEN_ENTRY',11.99)

SELECT * FROM ITEMS

SELECT * FROM FISHTAIL_MENU F RIGHT JOIN ITEMS I ON F.CATEGORY=I.CATEGORY







