--EXAMPLE OF STORE PROCEDURE 

drop table OM_BANK_ACCOUNT
go
create table OM_BANK_ACCOUNT
(
Acct_NO varchar (10) check ((left(Acct_NO,1)='B') and (Acct_NO like '_O%') and (Acct_NO like'__A%') and 
Acct_NO like '___[_]%' and (Len(Acct_NO)=8) and (substring(Acct_NO,5,len(Acct_NO))) not like '%[^0-9]%'),

First_Name Varchar (20),
Balance float 
)

INSERT INTO OM_BANK_ACCOUNT VALUES
('BOA_4564','RANDY',5000.45),
('BOA_3001','KAYNA',7569.23),
('BOA_4567','HENRY',4500.25)

select * from OM_BANK_ACCOUNT


-------------------
drop table OM_TRANSACTION
CREATE TABLE OM_TRANSACTION 
(
Acct_NO varchar (10) check ((left(Acct_NO,1)='B') and (Acct_NO like '_O%') and (Acct_NO like'__A%') and 
Acct_NO like '___[_]%' and (Len(Acct_NO)=8) and (substring(Acct_NO,5,len(Acct_NO))) not like '%[^0-9]%'),
Activity Varchar (20) check (Activity='Withdraw' or Activity='Deposit'),
Amount float,
Transaction_Date Datetime
)

DROP PROCEDURE OM_SP_INSERT_OM_TRANSACTION

create procedure OM_SP_INSERT_OM_TRANSACTION
(@ACCT_NO VARCHAR (10), @ACTIVITY VARCHAR (20),@AMOUNT FLOAT)

AS 
BEGIN

	IF ((SELECT COUNT(*) FROM OM_BANK_ACCOUNT WHERE ACCT_NO = @ACCT_NO) > 0)  -- THIS WILL CHECK IF THAT ACCT_NO IS THERE OR AS IF WE ARE USING PRIMARY KEY AND FK
		BEGIN
		IF (@ACTIVITY = 'DEPOSIT') and @amount<=500   ---CAN DEPOSIT EQUAL OR LESS THEN 500 ONLY
		BEGIN
		INSERT INTO OM_TRANSACTION VALUES (@ACCT_NO,@ACTIVITY,@AMOUNT,GETDATE())

		UPDATE OM_BANK_ACCOUNT
		SET BALANCE = BALANCE + @AMOUNT FROM OM_BANK_ACCOUNT WHERE ACCT_NO = @ACCT_NO
		END

		ELSE
		BEGIN
			IF ( (SELECT BALANCE FROM OM_BANK_ACCOUNT WHERE ACCT_NO = @ACCT_NO) >@AMOUNT) and @amount  <=500 ---CAN WITHDRAW EQUAL OR LESS THEN 500 ONLY
				BEGIN
					INSERT INTO OM_TRANSACTION VALUES (@ACCT_NO, @ACTIVITY,@AMOUNT, GETDATE())

					UPDATE OM_BANK_ACCOUNT
					SET BALANCE = BALANCE - @AMOUNT FROM OM_BANK_ACCOUNT WHERE ACCT_NO = @ACCT_NO
				END

		END

		END 
END  -- END OF STORE PROCEDURE




EXEC OM_SP_INSERT_OM_TRANSACTION 'BOA_5001','DEPOSIT',100 -- ACCT_NO NOT EXIST
SELECT * FROM OM_BANK_ACCOUNT
SELECT * FROM OM_TRANSACTION


EXEC OM_SP_INSERT_OM_TRANSACTION 'BOA_4561','WITHDRAW',500 -- ACCT_NO NOT EXIST
SELECT * FROM OM_BANK_ACCOUNT
SELECT * FROM OM_TRANSACTION


EXEC OM_SP_INSERT_OM_TRANSACTION 'BOA_4564','WITHDRAW',400
SELECT * FROM OM_BANK_ACCOUNT
SELECT * FROM OM_TRANSACTION



EXEC OM_SP_INSERT_OM_TRANSACTION 'BOA_4564','DEPOSIT',500
SELECT * FROM OM_BANK_ACCOUNT
SELECT * FROM OM_TRANSACTION


TRUNCATE TABLE OM_BANK_ACCOUNT
TRUNCATE TABLE OM_TRANSACTION
