DROP TABLE OM_EMPLOYEE
CREATE TABLE OM_EMPLOYEE
(
EMP_ID INT IDENTITY(1,1),
EMP_NUM INT,
EMP_FIRST_NAME VARCHAR(20),
DOB DATE
)

INSERT INTO OM_EMPLOYEE VALUES 
(1001, 'TOM', '2001-2-23'),
(1002, 'SAM', '2001-2-23'),
(1002, 'SHYAM', '2001-12-23'),
(1002, 'HARRY', '2002-2-07'),
(1003, 'TOM', '2001-2-23'),
(1003, 'TOM', '2001-2-23'),
(1003, 'TOM', '2001-2-23'),
(1003, 'TOM', '2001-2-23'),
(1004, 'ROBER', '2012-5-24'),
(1004, 'ROBERT JR', '2012-5-24'),
(1005, 'KELLY', '1989-9-04')

SELECT EMP_NUM, EMP_FIRST_NAME , DOB FROM OM_EMPLOYEE

SELECT EMP_ID, EMP_NUM , EMP_FIRST_NAME --, DOB, 
,ROW_NUMBER() OVER(PARTITION BY EMP_NUM  ORDER BY EMP_NUM DESC) AS SERIAL_NO
INTO #TEMP
FROM OM_EMPLOYEE

SELECT * FROM #TEMP

DROP TABLE #TEMP_REMOVING_DUPLICATE
SELECT EMP_ID, EMP_NUM , EMP_FIRST_NAME INTO #TEMP_REMOVING_DUPLICATE FROM #TEMP WHERE SERIAL_NO = 1

SELECT * FROM #TEMP_REMOVING_DUPLICATE


SELECT EMP_ID, EMP_NUM , EMP_FIRST_NAME --, DOB, 
,ROW_NUMBER() OVER(PARTITION BY EMP_NUM  ORDER BY EMP_FIRST_NAME ASC) AS SERIAL_NO
--INTO #TEMP
FROM OM_EMPLOYEE

SELECT EMP_ID, EMP_NUM , EMP_FIRST_NAME --, DOB, 
,ROW_NUMBER() OVER(PARTITION BY EMP_NUM  ORDER BY EMP_FIRST_NAME) AS SERIAL_NO
--INTO #TEMP
FROM OM_EMPLOYEE

SELECT * FROM #TEMP
SELECT EMP_ID, EMP_NUM, EMP_FIRST_NAME , DOB FROM #TEMP WHERE SERIAL_NO = 1


SELECT EMP_ID, EMP_NUM, EMP_FIRST_NAME , DOB, 
ROW_NUMBER() OVER(PARTITION BY EMP_NUM  ORDER BY EMP_NUM ASC) AS SERIAL_NO
--,ROW_NUMBER() OVER(PARTITION BY EMP_NUM  ORDER BY EMP_ID DESC) AS SERIAL_NO
FROM OM_EMPLOYEE

SELECT EMP_ID, EMP_NUM, EMP_FIRST_NAME , DOB
,ROW_NUMBER() OVER(PARTITION BY EMP_NUM  ORDER BY EMP_ID DESC) AS SERIAL_NO
INTO #TEMP2
FROM OM_EMPLOYEE

SELECT * FROM #TEMP2
SELECT EMP_ID, EMP_NUM, EMP_FIRST_NAME , DOB FROM #TEMP2 WHERE SERIAL_NO = 1





