SELECT EMPID,EMPNAME FROM EMP_NEPAL 
UNION
SELECT EID,ENAME FROM EMP_US  ORDER BY EMPID
SELECT * FROM EMP_NEPAL
SELECT * FROM EMP_US
--DISPLAY ALL EMPLOYEES INFORMATION INCLUDING DUPLICATES

SELECT EMPID,EMPNAME FROM EMP_NEPAL 
UNION ALL
SELECT EID,ENAME FROM EMP_US  ORDER BY EMPID
--DISPLAY EMPLOYEES WHO ARE WORKING IN BOTH PLACES
SELECT EID,ENAME FROM EMP_US  
INTERSECT
SELECT EMPID,EMPNAME FROM EMP_NEPAL ORDER BY EID

--DISPLAY EMPLOYEES WHO ARE WORKING IN ONLY INDIA BIT IN US
SELECT EMPID,EMPNAME FROM EMP_NEPAL 
EXCEPT
SELECT EID,ENAME FROM EMP_US  

--DISPLAY EMPLOYEES WHO ARE WORKING IN ONLY US BIT IN INDIA

SELECT EID,ENAME FROM EMP_US  
EXCEPT
SELECT EMPID,EMPNAME FROM EMP_NEPAL
