DROP TABLE OM_EMPLOYEE
CREATE TABLE OM_EMPLOYEE
(
	EMP_ID INT PRIMARY KEY,
	EMP_NAME VARCHAR(20)
)
 
INSERT INTO OM_EMPLOYEE VALUES (1, 'GIA')
INSERT INTO OM_EMPLOYEE VALUES (2, 'SUMAN')
INSERT INTO OM_EMPLOYEE VALUES (3, 'DHAN')
INSERT INTO OM_EMPLOYEE VALUES (4, 'JOYA')

SELECT * FROM om_employee1
SELECT * FROM OM_EMPLOYEE

DROP VIEW V_OM_EMPLOYEE
CREATE VIEW V_OM_EMPLOYEE
AS
SELECT * FROM OM_EMPLOYEE 

SELECT * FROM V_OM_EMPLOYEE

INSERT INTO V_OM_EMPLOYEE VALUES (1, 'GIA')
INSERT INTO V_OM_EMPLOYEE VALUES (2, 'SUMAN')

UPDATE V_OM_EMPLOYEE SET EMP_NAME = 'TEST' WHERE EMP_ID = 1

DELETE FROM V_OM_EMPLOYEE   WHERE EMP_ID = 3

---------------hw

CREATE VIEW V_OM_EMPLOYEE
AS
SELECT t1.EMP_ID, t2.EMP_NAME, t2.emp_name FROM OM_EMPLOYEE t1 join om_employee1 t2
on t1.emp_id = t2.employeeid


CREATE VIEW V_OM_EMPLOYEE
AS
SELECT t1.ID, t2.first_Name FROM OM_EMPLOYEE t1 LEFT join om_employee1 t2
on t1.ID = t2.EMPID




